import { StyleSheet } from "react-native";

import { fs, hs, ms, vs } from "@constants";
import { colorStyle } from "@constants/colors";

export const MATCHED_COLORS = {
  bgTop: colorStyle.Main2,
  bgBottom: colorStyle.Main,
  borderSoft: "#C7D0FF",
  bubbleYellow: "#FFF195",
  bubbleYellowBorder: "#FFF6C2",
  textBody: "#1F1F1F",
  textMuted: "#828282",
  timeText: "#2C457F",
} as const;

export const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  screen: {
    flex: 1,
    width: "100%",
  },
  header: {
    paddingTop: vs(18),
    paddingHorizontal: hs(20),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  logo: {
    width: hs(96),
    height: vs(36),
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: hs(16),
  },
  headerIconHit: {
    width: hs(30),
    height: hs(30),
    alignItems: "center",
    justifyContent: "center",
  },
  statusSection: {
    marginTop: vs(30),
    paddingHorizontal: hs(20),
  },
  statusCardSelf: {
    flexDirection: "row",
    alignItems: "center",
    gap: hs(10),
    minHeight: vs(71),
    paddingRight: hs(20),
    paddingLeft: hs(10),
    paddingVertical: vs(8),
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: MATCHED_COLORS.borderSoft,
    borderTopLeftRadius: ms(30),
    borderTopRightRadius: ms(97),
    borderBottomRightRadius: ms(97),
    borderBottomLeftRadius: ms(30),
  },
  statusCardRoommateWrap: {
    marginTop: vs(13),
    alignSelf: "flex-end",
    width: "70%",
  },
  statusCardRoommate: {
    flexDirection: "row",
    alignItems: "center",
    gap: hs(10),
    minHeight: vs(68),
    paddingRight: hs(16),
    paddingLeft: hs(10),
    paddingVertical: vs(8),
    backgroundColor: MATCHED_COLORS.bubbleYellow,
    borderWidth: 1,
    borderColor: MATCHED_COLORS.bubbleYellowBorder,
    borderTopLeftRadius: ms(30),
    borderTopRightRadius: ms(97),
    borderBottomRightRadius: ms(97),
    borderBottomLeftRadius: ms(30),
  },
  statusAvatar: {
    width: hs(55),
    height: hs(55),
    borderRadius: hs(27.5),
  },
  statusTextWrap: {
    flex: 1,
    gap: vs(2),
  },
  statusName: {
    fontSize: fs(18),
    lineHeight: fs(25),
    color: MATCHED_COLORS.textBody,
    letterSpacing: -0.54,
  },
  statusMessage: {
    fontSize: fs(14),
    lineHeight: fs(20),
    color: MATCHED_COLORS.textBody,
    letterSpacing: -0.42,
  },
  scheduleSection: {
    flex: 1,
    marginTop: vs(16),
    alignSelf: "stretch",
    width: "100%",
  },
  arcPanel: {
    flex: 1,
    alignSelf: "stretch",
    width: "100%",
    marginTop: vs(8),
    backgroundColor: colorStyle.Main2,
    borderTopLeftRadius: ms(999),
    borderTopRightRadius: ms(999),
    paddingTop: vs(28),
    overflow: "hidden",
  },
  arcPanelContent: {
    paddingHorizontal: hs(20),
  },
  arcDatesRow: {
    height: vs(88),
    width: "100%",
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  arcDateSide: {
    position: "absolute",
    fontSize: fs(20),
    lineHeight: fs(28),
    color: colorStyle.black,
    opacity: 0.4,
    letterSpacing: -0.4,
  },
  arcDateLeftFar: {
    left: hs(8),
    bottom: vs(4),
    transform: [{ rotate: "-37deg" }],
  },
  arcDateLeftNear: {
    left: hs(72),
    top: vs(8),
    transform: [{ rotate: "-32deg" }],
  },
  arcDateRightNear: {
    right: hs(72),
    top: vs(8),
    transform: [{ rotate: "26deg" }],
  },
  arcDateRightFar: {
    right: hs(8),
    bottom: vs(4),
    transform: [{ rotate: "45deg" }],
  },
  arcDateCenter: {
    fontSize: fs(40),
    lineHeight: fs(56),
    color: colorStyle.black,
    letterSpacing: -0.8,
  },
  monthWeekWrap: {
    alignItems: "center",
    marginTop: vs(4),
    gap: vs(2),
  },
  monthLabel: {
    fontSize: fs(20),
    lineHeight: fs(28),
    color: colorStyle.Main_Text,
    letterSpacing: -0.6,
  },
  weekdayLabel: {
    fontSize: fs(16),
    lineHeight: fs(22),
    color: colorStyle.Sub1,
    letterSpacing: -0.48,
  },
  daySummary: {
    marginTop: vs(12),
    fontSize: fs(14),
    lineHeight: fs(20),
    color: MATCHED_COLORS.textMuted,
    letterSpacing: -0.42,
    textAlign: "center",
  },
  listBottomFade: {
    alignSelf: "stretch",
    width: "100%",
    height: vs(100),
    marginTop: "auto",
  },
  choreList: {
    marginTop: vs(20),
    gap: vs(16),
  },
  choreRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: hs(12),
  },
  choreIcon: {
    width: hs(50),
    height: hs(50),
  },
  choreBody: {
    flex: 1,
    gap: vs(2),
  },
  choreTitle: {
    fontSize: fs(16),
    lineHeight: fs(22),
    color: MATCHED_COLORS.textBody,
    letterSpacing: -0.48,
  },
  choreTime: {
    fontSize: fs(20),
    lineHeight: fs(28),
    color: MATCHED_COLORS.timeText,
    letterSpacing: -0.4,
  },
  choreAssignee: {
    fontSize: fs(16),
    lineHeight: fs(22),
    color: MATCHED_COLORS.textMuted,
    letterSpacing: -0.48,
    minWidth: hs(40),
    textAlign: "right",
  },
  choreDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: colorStyle.S03,
    marginTop: vs(20),
  },
  devToggle: {
    position: "absolute",
    right: hs(12),
    top: vs(84),
    zIndex: 10,
    backgroundColor: "rgba(21, 23, 27, 0.72)",
    borderRadius: ms(8),
    paddingHorizontal: hs(10),
    paddingVertical: vs(6),
  },
  devToggleText: {
    fontSize: fs(11),
    lineHeight: fs(14),
    color: "#FFFFFF",
    letterSpacing: -0.2,
  },
});
