import { StyleSheet } from "react-native";

import { colorStyle } from "../../../constants/colors";
import type { ScaleFns } from "../../../constants/create-scale-api";
import { figmaLetterSpacing } from "../../../constants/matching-figma";

export const createRoommateDetailStyles = ({ hs, vs, fs, ms }: ScaleFns) =>
  StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colorStyle.Main2,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      paddingBottom: vs(120),
    },
    header: {
      paddingLeft: hs(15),
      paddingTop: vs(27),
      paddingBottom: vs(10),
    },
    profileRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: hs(24),
      paddingHorizontal: hs(20),
      paddingBottom: vs(16),
    },
    avatarWrap: {
      width: hs(65),
      height: hs(65),
    },
    avatar: {
      width: hs(65),
      height: hs(65),
      borderRadius: hs(32.5),
    },
    onlineDot: {
      position: "absolute",
      top: 0,
      right: 0,
      width: hs(11.51),
      height: hs(11.51),
      borderRadius: hs(5.755),
      backgroundColor: colorStyle.Sub1,
      borderWidth: hs(2.5),
      borderColor: "#FFFFFF",
    },
    profileText: {
      flex: 1,
      gap: vs(8),
    },
    name: {
      fontSize: fs(24),
      lineHeight: vs(24),
      letterSpacing: figmaLetterSpacing(24, -4),
      color: colorStyle.Main_Text,
    },
    matchSummary: {
      fontSize: fs(16),
      lineHeight: vs(16 * 1.5),
      letterSpacing: figmaLetterSpacing(16, -4),
      color: colorStyle.S05,
    },
    arcBackground: {
      position: "relative",
      marginTop: vs(-16),
      marginHorizontal: hs(1),
      minHeight: vs(313),
      borderTopLeftRadius: hs(200),
      borderTopRightRadius: hs(200),
      overflow: "hidden",
      alignItems: "center",
    },
    arcGradient: {
      ...StyleSheet.absoluteFillObject,
    },
    matchSection: {
      width: "100%",
      alignItems: "center",
      paddingTop: vs(70),
      paddingBottom: vs(16),
    },
    matchRateBlock: {
      width: hs(206),
      alignItems: "center",
      gap: vs(18),
    },
    matchLabel: {
      fontSize: fs(20),
      lineHeight: vs(20 * 1.2),
      letterSpacing: figmaLetterSpacing(20, -4),
      color: colorStyle.Main_Text,
      textAlign: "center",
    },
    matchRateRow: {
      flexDirection: "row",
      alignItems: "flex-end",
      justifyContent: "center",
      minHeight: vs(80),
    },
    matchRateValue: {
      fontSize: fs(80),
      lineHeight: vs(80),
      letterSpacing: figmaLetterSpacing(80, -4),
      color: colorStyle.Sub1,
      includeFontPadding: false,
    },
    matchRateSuffix: {
      fontSize: fs(20),
      lineHeight: vs(20 * 1.2),
      letterSpacing: figmaLetterSpacing(20, -4),
      color: colorStyle.Sub1,
      marginBottom: vs(8),
      marginLeft: hs(2),
      includeFontPadding: false,
    },
    tagsWrap: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "center",
      gap: hs(4),
      rowGap: vs(7),
      maxWidth: hs(206),
      marginTop: vs(30),
    },
    tagChip: {
      backgroundColor: "#E6EEFF",
      borderRadius: ms(15),
      paddingVertical: vs(6),
      paddingHorizontal: hs(14),
    },
    tagChipText: {
      fontSize: fs(16),
      lineHeight: vs(16 * 1.25),
      letterSpacing: figmaLetterSpacing(16, -3),
      color: colorStyle.Main_Text,
    },
    contentSection: {
      paddingHorizontal: hs(20),
      paddingTop: vs(40),
      gap: vs(40),
      alignItems: "center",
    },
    introCardOuter: {
      borderRadius: ms(20),
      padding: hs(1),
      width: "100%",
      maxWidth: hs(353),
    },
    introCardInner: {
      borderRadius: ms(19),
      paddingVertical: vs(20),
      paddingHorizontal: hs(25),
      gap: vs(16),
      alignItems: "center",
      backgroundColor: "#FFFCEF",
    },
    introTitle: {
      fontSize: fs(18),
      lineHeight: vs(18 * 1.333),
      letterSpacing: figmaLetterSpacing(18, -4),
      color: "#C3B058",
      paddingBottom: vs(2),
      borderBottomWidth: hs(1),
      borderBottomColor: "#CAB65B",
    },
    introBodyWrap: {
      width: "100%",
      alignItems: "center",
      gap: 0,
    },
    introBodyLine: {
      fontSize: fs(15),
      lineHeight: vs(15 * 1.65),
      letterSpacing: figmaLetterSpacing(15, -4),
      color: "#1D1D1D",
      textAlign: "center",
    },
    divider: {
      width: hs(352),
      height: hs(1.5),
      backgroundColor: "#ECF0F8",
    },
    preferencesSection: {
      width: "100%",
      maxWidth: hs(300),
      alignItems: "center",
      gap: vs(21),
    },
    preferencesTitle: {
      fontSize: fs(18),
      lineHeight: vs(18 * 1.4),
      letterSpacing: figmaLetterSpacing(18, -4),
      color: "#4B566A",
      textAlign: "center",
    },
    preferencesList: {
      width: "100%",
      gap: vs(14),
    },
    preferenceChipOuter: {
      borderRadius: ms(999),
      padding: hs(1),
    },
    preferenceChipInner: {
      borderRadius: ms(998),
      paddingVertical: vs(14),
      paddingHorizontal: hs(10),
      backgroundColor: "#FFFFFF",
      alignItems: "center",
    },
    preferenceChipText: {
      fontSize: fs(18),
      lineHeight: vs(18 * 1.4),
      letterSpacing: figmaLetterSpacing(18, -4),
      color: colorStyle.Main_Text,
      textAlign: "center",
    },
    footer: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "#FFFFFF",
      paddingTop: vs(20),
      paddingHorizontal: hs(20),
    },
    footerRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: hs(12),
    },
    favoriteButton: {
      width: hs(62),
      height: vs(56),
      borderRadius: ms(20),
      overflow: "hidden",
    },
    favoriteIcon: {
      width: hs(62),
      height: vs(56),
    },
    ctaButton: {
      flex: 1,
      height: vs(56),
      backgroundColor: colorStyle.Sub3,
      borderRadius: ms(15),
      alignItems: "center",
      justifyContent: "center",
    },
    ctaText: {
      fontSize: fs(20),
      lineHeight: vs(20 * 1.4),
      letterSpacing: figmaLetterSpacing(20, -4),
      color: colorStyle.Main_Text,
    },
  });
